#if (NOT MINGW_COMPILER_PREFIX)
#    message(FATAL_ERROR "MINGW_COMPILER_PREFIX is not set. Aborting...")
#endif ()

#if (NOT MINGW_ROOT_PATH)
#    message(FATAL_ERROR "MINGW_ROOT_PATH  is not set. Aborting...")
#endif ()

set(CMAKE_SYSTEM_NAME Windows)

find_program(CMAKE_C_COMPILER NAMES ${MINGW_COMPILER_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER NAMES ${MINGW_COMPILER_PREFIX}-g++)
find_program(CMAKE_RC_COMPILER NAMES ${MINGW_COMPILER_PREFIX}-windres)

set(CMAKE_FIND_ROOT_PATH "${MINGW_ROOT_PATH}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

link_directories(${LINK_DIRECTORIES} "${MINGW_ROOT_PATH}")
